# Generated by Django 5.2.16 on 2026-07-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentchunk",
            name="context",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="documentchunk",
            name="embedding",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="researchsession",
            name="claims",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="researchtask",
            name="rounds_completed",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="researchtask",
            name="tokens_used",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="source",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
